export const songs = [
  { id: "dont-forget", title: "Don't Forget", chapter: 1 },
  { id: "beginning", title: "Beginning", chapter: 1 },
  { id: "faint-glow", title: "Faint Glow", chapter: 2 },
  { id: "friendship", title: "Friendship", chapter: 1 },
  { id: "scarlet-forest", title: "Scarlet Forest", chapter: 1 },
  { id: "until-next-time", title: "Until Next Time", chapter: 3 },
  { id: "your-power", title: "Your Power", chapter: 1 },
  { id: "field-of-hopes-and-dreams", title: "Field of Hopes and Dreams", chapter: 1 },
  { id: "garden-of-hopes-and-dreams", title: "Garden of Hopes and Dreams", chapter: 5 },
  { id: "the-legend", title: "The Legend", chapter: 1 },
  { id: "the-door", title: "The Door", chapter: 1 },
  { id: "chase", title: "Chase", chapter: 1 },
  { id: "once-upon-a-time", title: "Once Upon a Time", chapter: 8 },
  { id: "before-the-story", title: "Before the Story", chapter: 2 },
  { id: "the-world-revolving", title: "The World Revolving", chapter: 1 },
  { id: "dialtone", title: "Dialtone", chapter: 2 },
  { id: "the-circus", title: "Circus", chapter: 1 },
  { id: "cutie-mew-mew-magic", title: "Cutie Mew Mew Magic", chapter: 5 },
  { id: "a-town-called-hometown", title: "A Town Called Hometown", chapter: 1 },
  { id: "another-day-in-hometown", title: "Another Day In Hometown", chapter: 4 },
  { id: "school", title: "School", chapter: 1 },
  { id: "black-knife", title: "Black Knife", chapter: 3 },
  { id: "castle-funk", title: "Castle Funk", chapter: 3 },
  { id: "my-castle-town", title: "My Castle Town", chapter: 2 },
  { id: "dark-sanctuary", title: "Dark Sanctuary", chapter: 4 },
  { id: "the-second-sanctuary", title: "The Second Sanctuary", chapter: 4 },
  { id: "chaos-king", title: "Chaos King", chapter: 1 },
  { id: "empty-town", title: "Empty Town", chapter: 1 },
  { id: "the-legend?", title: "The LEGEND...?", chapter: 4 },
  { id: "the-third-sanctuary", title: "The Third Sanctuary", chapter: 4 },
  { id: "a-dark-zone", title: "A DARK ZONE", chapter: 4 },
  { id: "another-him", title: "ANOTHER HIM", chapter: 1 },
  { id: "susie", title: "Susie", chapter: 1 },
  { id: "cliffs", title: "Cliffs", chapter: 1 },
  { id: "lancer", title: "Lancer", chapter: 1 },
  { id: "rude-buster", title: "Rude Buster", chapter: 1 },
  { id: "weird-birds", title: "Weird Birds", chapter: 1 },
  { id: "fanfare-from-rose-of-winter", title: "Fanfare (from Rose of Winter)", chapter: 1 },
  { id: "lantern", title: "Lantern", chapter: 1 },
  { id: "im-very-bad", title: "I'm Very Bad", chapter: 1 },
  { id: "checker-dance", title: "Checker Dance", chapter: 1 },
  { id: "quiet-autumn", title: "Quiet Autumn", chapter: 1 },
  { id: "thrash-machine", title: "Thrash Machine", chapter: 1 },
  { id: "vs-lancer", title: "Vs. Lancer", chapter: 1 },
  { id: "basement", title: "Basement", chapter: 1 },
  { id: "imminent-death", title: "Imminent Death", chapter: 1 },
  { id: "vs-susie", title: "Vs. Susie", chapter: 1 },
  { id: "card-castle", title: "Card Castle", chapter: 1 },
  { id: "rouxls-kaard", title: "Rouxls Kaard", chapter: 1 },
  { id: "april-2012", title: "April 2012", chapter: 1 },
  { id: "hip-shop", title: "Hip Shop", chapter: 1 },
  { id: "gallery", title: "Gallery", chapter: 1 },
  { id: "darkness-falls", title: "Darkness Falls", chapter: 1 },
  { id: "the-holy", title: "THE HOLY", chapter: 1 },
  { id: "you-can-always-come-home", title: "You Can Always Come Home", chapter: 1 },

  { id: "girl-next-door", title: "Girl Next Door", chapter: 2 },
  { id: "ohhhhohohoho", title: "Ohhhhohohoho!", chapter: 2 },
  { id: "queen", title: "Queen", chapter: 2 },
  { id: "a-cybers-world", title: "A CYBER'S WORLD?", chapter: 2 },
  { id: "a-simple-diversion", title: "A Simple Diversion", chapter: 2 },
  { id: "almost-to-the-guys", title: "Almost To The Guys!", chapter: 2 },
  { id: "cool-beat", title: "Cool Beat", chapter: 2 },
  { id: "when-i-get-mad-i-dance-like-this", title: "When I Get Mad I Dance Like This", chapter: 2 },
  { id: "cyber-battle-solo", title: "Cyber Battle (Solo)", chapter: 2 },
  { id: "when-i-get-happy-i-dance-like-this", title: "When I Get Happy I Dance Like This", chapter: 2 },
  { id: "sound-studio", title: "Sound Studio", chapter: 2 },
  { id: "berdly", title: "Berdly", chapter: 2 },
  { id: "smart-race", title: "Smart Race", chapter: 2 },
  { id: "faint-courage", title: "Faint Courage (Game Over)", chapter: 2 },
  { id: "welcome-to-the-city", title: "WELCOME TO THE CITY", chapter: 2 },
  { id: "mini-studio", title: "Mini Studio", chapter: 2 },
  { id: "holiday-studio", title: "Holiday Studio", chapter: 2 },
  { id: "cool-mixtape", title: "Cool Mixtape", chapter: 2 },
  { id: "hey-every", title: "HEY EVERY !", chapter: 2 },
  { id: "spamton", title: "Spamton", chapter: 2 },
  { id: "nows-your-chance-to-be-a", title: "NOW'S YOUR CHANCE TO BE A", chapter: 2 },
  { id: "elegant-entrance", title: "Elegant Entrance", chapter: 2 },
  { id: "bluebird-of-misfortune", title: "Bluebird of Misfortune", chapter: 2 },
  { id: "pandora-palace", title: "Pandora Palace", chapter: 2 },
  { id: "keygen", title: "KEYGEN", chapter: 2 },
  { id: "acid-tunnel-of-love", title: "Acid Tunnel of Love", chapter: 2 },
  { id: "its-pronounced-rules", title: "It's Pronounced \"Rules\"", chapter: 2 },
  { id: "lost-girl", title: "Lost Girl", chapter: 2 },
  { id: "ferris-wheel", title: "Ferris Wheel", chapter: 2 },
  { id: "attack-of-the-killer-queen", title: "Attack of the Killer Queen", chapter: 2 },
  { id: "giga-size", title: "Giga Size", chapter: 2 },
  { id: "powers-combined", title: "Powers Combined", chapter: 2 },
  { id: "knock-you-down", title: "Knock You Down !!", chapter: 2 },
  { id: "the-dark-truth", title: "The Dark Truth", chapter: 2 },
  { id: "digital-roots", title: "Digital Roots", chapter: 2 },
  { id: "deal-gone-wrong", title: "Deal Gone Wrong", chapter: 2 },
  { id: "big-shot", title: "BIG SHOT", chapter: 2 },
  { id: "a-real-boy", title: "A Real Boy!", chapter: 2 },
  { id: "sans", title: "sans.", chapter: 2 },
  { id: "chill-jailbreak-alarm-to-study-and-relax-to", title: "Chill Jailbreak Alarm To Study And Relax To", chapter: 2 },
  { id: "berdly-rejected-concept", title: "Berdly (Rejected Concept)", chapter: 2 },

  { id: "flashback-excerpt", title: "Flashback (Excerpt)", chapter: 3 },
  { id: "feature-presentation", title: "Feature Presentation", chapter: 3 },
  { id: "and-now-for-todays-sponsors", title: "And Now For Today's Sponsors…!", chapter: 3 },
  { id: "mike-the-board-please", title: "MIKE, the BOARD, please!", chapter: 3 },
  { id: "sandy-board", title: "Sandy Board", chapter: 3 },
  { id: "adventure-board", title: "Adventure Board", chapter: 3 },
  { id: "query", title: "Query?", chapter: 3 },
  { id: "quiz", title: "Quiz!", chapter: 3 },
  { id: "dig-dig-to-the-center-of-the-earth", title: "Dig! Dig! To The Center of the Earth!", chapter: 3 },
  { id: "pushing-buddies", title: "Pushing Buddies", chapter: 3 },
  { id: "ruder-buster", title: "Ruder Buster", chapter: 3 },
  { id: "physical-challenge", title: "Physical Challenge", chapter: 3 },
  { id: "board-clear", title: "Board Clear!", chapter: 3 },
  { id: "welcome-to-the-green-room", title: "Welcome to the Green Room", chapter: 3 },
  { id: "vapor-buster", title: "Vapor Buster", chapter: 3 },
  { id: "paradise-paradise", title: "Paradise, Paradise", chapter: 3 },
  { id: "raft-ride", title: "Raft Ride", chapter: 3 },
  { id: "south-of-the-border", title: "SOUTH OF THE BORDER!!", chapter: 3 },
  { id: "sound-check", title: "Sound Check", chapter: 3 },
  { id: "raise-up-your-bat", title: "Raise Up Your Bat", chapter: 3 },
  { id: "king-of-rolypoly", title: "KING OF ROLYPOLY", chapter: 3 },
  { id: "glowing-snow", title: "Glowing Snow", chapter: 3 },
  { id: "big-city-board", title: "Big City Board", chapter: 3 },
  { id: "doom-board", title: "Doom Board", chapter: 3 },
  { id: "metaphysical-challenge", title: "Metaphysical Challenge", chapter: 3 },
  { id: "tv-world", title: "TV WORLD", chapter: 3 },
  { id: "its-tv-time", title: "It's TV Time!", chapter: 3 },
  { id: "hall-of-fame", title: "Hall of Fame", chapter: 3 },
  { id: "breath", title: "Breath", chapter: 3 },
  { id: "crickets", title: "Crickets", chapter: 3 },
  { id: "dump", title: "Dump", chapter: 3 },
  { id: "sword", title: "SWORD", chapter: 3 },
  { id: "northernlight", title: "NORTHERNLIGHT", chapter: 3 },
  { id: "glaceir", title: "GLACEIR", chapter: 3 },
  { id: "bit-roots", title: "BIT ROOTS", chapter: 3 },
  { id: "eram", title: "ERAM", chapter: 3 },
  { id: "burning-eyes", title: "BURNING EYES", chapter: 3 },

  { id: "old-wooden-rafters", title: "Old wooden rafters", chapter: 4 },
  { id: "hymn", title: "Hymn", chapter: 4 },
  { id: "friends", title: "Friends", chapter: 4 },
  { id: "knock-you-down-rhythm-ver", title: "Knock You Down!! (Rhythm Ver.)", chapter: 4 },
  { id: "gingerbread-house", title: "Gingerbread House", chapter: 4 },
  { id: "the-distance-between-two", title: "The distance between two", chapter: 4 },
  { id: "c", title: "C", chapter: 4 },
  { id: "atrium", title: "ATRIUM", chapter: 4 },
  { id: "from-now-on", title: "From Now On (Battle 2)", chapter: 4 },
  { id: "gyaa-ha-ha", title: "Gyaa Ha ha!", chapter: 4 },
  { id: "fireplace", title: "Fireplace", chapter: 4 },
  { id: "mysterious-ringing", title: "Mysterious Ringing", chapter: 4 },
  { id: "ever-higher", title: "Ever Higher", chapter: 4 },
  { id: "wise-words", title: "Wise words", chapter: 4 },
  { id: "piano-that-may-not-be-played-that-well", title: "Piano that may not be played that well", chapter: 4 },
  { id: "hammer-of-justice", title: "Hammer of Justice", chapter: 4 },
  { id: "12am", title: "12am", chapter: 4 },
  { id: "ripple", title: "Ripple", chapter: 4 },
  { id: "13am", title: "13am", chapter: 4 },
  { id: "dark-place", title: "Dark Place", chapter: 4 },
  { id: "heavy-footsteps", title: "Heavy Footsteps", chapter: 4 },
  { id: "crumbling-tower", title: "Crumbling Tower", chapter: 4 },
  { id: "spawn", title: "SPAWN", chapter: 4 },
  { id: "guardian", title: "GUARDIAN", chapter: 4 },
  { id: "need-a-hand", title: "Need a hand!?", chapter: 4 },
  { id: "the-place-where-it-rained", title: "The place where it rained", chapter: 4 },
  { id: "the-ol-jitterbug", title: "The Ol’ Jitterbug", chapter: 4 },
  { id: "neverending-night", title: "Neverending Night", chapter: 4 },
  { id: "with-hope-crossed-on-our-hearts", title: "With Hope Crossed On Our Hearts", chapter: 4 },
  { id: "volume-adjustment", title: "Volume Adjustment", chapter: 4 },
  { id: "catswing", title: "Catswing", chapter: 4 },
  { id: "airwaves", title: "AIRWAVES", chapter: 4 },
  { id: "concert-for-you", title: "Concert for you", chapter: 4 },

  { id: "chapter-5-logo", title: "Chapter 5 Logo", chapter: 5 },
  { id: "inappropriate-recycling", title: "Inappropriate Recycling", chapter: 5 },
  { id: "pirate-dojo", title: "Pirate Dojo", chapter: 5 },
  { id: "4rd-sanctuary", title: "4rd Sanctuary", chapter: 5 },
  { id: "festival", title: "Festival", chapter: 5 },
  { id: "catfession", title: "Catfession...?", chapter: 5 },
  { id: "bratfession", title: "Bratfession...?", chapter: 5 },
  { id: "i-guess-im-in-love", title: "I guess I'm in love", chapter: 5 },
  { id: "weirder-birds", title: "Weirder Birds", chapter: 5 },
  { id: "your-dads-best-friend", title: "Your Dad's Best Friend", chapter: 5 },
  { id: "rakuichi-buster", title: "Rakuichi Buster", chapter: 5 },
  { id: "the-diner-song-of-best-friends", title: "The Diner Song of Best Friends", chapter: 5 },
  { id: "ride-the-board", title: "Ride the Board", chapter: 5 },
  { id: "quiet-glade", title: "Quiet Glade", chapter: 5 },
  { id: "who-might-you-be", title: "Who might you be?", chapter: 5 },
  { id: "petal-dance", title: "Petal Dance", chapter: 5 },
  { id: "flying-feather", title: "Flying Feather", chapter: 5 },
  { id: "sunset-of-seven-suns", title: "Sunset of Seven Suns", chapter: 5 },
  { id: "shop-3", title: "Shop 3", chapter: 5 },
  { id: "violet-tactics", title: "Violet Tactics", chapter: 5 },
  { id: "flower-king", title: "Flower King", chapter: 5 },
  { id: "flower-foyer", title: "Flower Foyer", chapter: 5 },
  { id: "flower-castle", title: "Flower Castle", chapter: 5 },
  { id: "thousand-cafe-zukan", title: "Thousand Cafe Zukan", chapter: 5 },
  { id: "im-telling", title: "I'm Telling!", chapter: 5 },
  { id: "stop-criminell", title: "Stop, Criminell!", chapter: 5 },
  { id: "loving-steps", title: "Loving Steps", chapter: 5 },
  { id: "onsen", title: "Onsen", chapter: 5 },
  { id: "beautiful-bathtime", title: "Beautiful Bathtime", chapter: 5 },
  { id: "pink", title: "Pink", chapter: 5 },
  { id: "running-sky", title: "Running Sky", chapter: 5 },
  { id: "flower-man", title: "Flower Man", chapter: 5 },
  { id: "that-day", title: "That Day", chapter: 5 },
  { id: "dreamwatchers", title: "Dreamwatchers", chapter: 5 },
  { id: "weak-flowers", title: "Weak Flowers", chapter: 5 },
  { id: "walking-home", title: "Walking Home", chapter: 5 },
  { id: "field-of-hopes-and-dreams-credits-version", title: "Field of Hopes and Dreams (Credits Version)", chapter: 5 },
  { id: "goodnight-sweet-prince", title: "Goodnight, Sweet Prince", chapter: 5 },
  { id: "him", title: "Gaster's Theme", chapter: 8 },
  { id: "determination", title: "Determination", chapter: 8 },
  { id: "asgore", title: "ASGORE", chapter: 8 },
  { id: "your-best-nightmare", title: "YOUR BEST NIGHTMARE", chapter: 8 },
  { id: "hymm", title: "Hymm", chapter: 4 },

]

export const motifs = [
  {
    id: "dont-forget",
    name: "Don't Forget (motif)",
    color: "#ac4dff",
    source: "dont-forget",
    songs: [
      "dont-forget",
      "beginning",
      "faint-glow",
      "friendship",
      "scarlet-forest",
      "until-next-time",
      "your-power",
      "field-of-hopes-and-dreams",
      "garden-of-hopes-and-dreams",
      "the-world-revolving",
      "cutie-mew-mew-magic",
      "a-town-called-hometown",
      "another-day-in-hometown",
      "school",
      "castle-funk",
      "dark-sanctuary",
      "festival",
      "i-guess-im-in-love",
      "the-diner-song-of-best-friends",
      "with-hope-crossed-on-our-hearts",
      "hymm",
      "piano-that-may-not-be-played-that-well",
      "flower-man",
      "running-sky",
      "you-can-always-come-home",
      "the-dark-truth",
      "dark-place",
      "ever-higher",
      "from-now-on",
      "guardian",
      "crumbling-tower"
    ]
  },
  {
    id: "once-upon-a-time",
    name: "Once Upon a Time (motif)",
    color: "#cf3a3a",
    source: "once-upon-a-time",
    songs: [
      "beginning",
      "garden-of-hopes-and-dreams",
      "before-the-story",
      "once-upon-a-time"
    ]
  },
  {
    id: "chase",
    name: "Chase (motif)",
    color: "#151a75",
    source: "chase",
    songs: [
      "chase",
      "the-door",
      "the-world-revolving",
      "black-knife",
      "that-day"
    ]
  },
  {
    id: "freedom",
    name: "Freedom",
    color: "#ebaa2a",
    source: "the-world-revolving",
    songs: [
      "dialtone",
      "the-world-revolving",
      "the-circus",
      "cutie-mew-mew-magic",
      "big-shot",
      "hammer-of-justice",
      "inappropriate-recycling",
      "airwaves"
    ]
  },
  {
    id: "hometown",
    name: "Hometown",
    color: "#d8c091",
    source: "a-town-called-hometown",
    songs: [
      "a-town-called-hometown",
      "another-day-in-hometown",
      "school"
    ]
  },
  {
    id: "the-legend",
    name: "The Legend",
    color: "#ffffff",
    source: "the-legend",
    songs: [
      "the-legend",
      "castle-funk",
      "my-castle-town",
      "dark-sanctuary",
      "the-second-sanctuary",
      "chaos-king",
      "empty-town",
      "the-legend?",
      "a-dark-zone",
      "the-third-sanctuary"
    ]
  },
  {
    id: "dark-sanctuary",
    name: "Dark Sanctuary",
    color: "#2e0d4b",
    source: "dark-sanctuary",
    songs: [
      "dark-sanctuary",
      "the-second-sanctuary",
      "the-third-sanctuary",
      "from-now-on",
      "spawn",
      "ever-higher",
      "guardian",
      "crumbling-tower",
      "neverending-night"
    ]
  },
  {
    id: "tv-time",
    name: "TV Time",
    color: "#f67710",
    source: "feature-presentation",
    songs: [
      "feature-presentation",
      "hey-every",
      "tv-world",
      "its-tv-time",
      "dump",
      "a-real-boy",
      "catswing",
      "hall-of-fame"
    ]
  },
  {
    id: "lost-girl",
    name: "Lost Girl",
    color: "#2eabca",
    source: "lost-girl",
    songs: [
      "the-distance-between-two",
      "lost-girl",
      "girl-next-door",
      "gingerbread-house",
      "friends",
      "walking-home",
      "i-guess-im-in-love",
      "festival",
      "the-diner-song-of-best-friends"
    ]
  },
  {
    id: "gaster",
    name: "Gaster",
    color: "#000000",
    source: "him",
    songs: [
      "lost-girl",
      "another-him",
      "darkness-falls",
      "the-world-revolving",
    ]
  },
  {
    id: "determination",
    name: "Determination",
    color: "#ff0022",
    source: "determination",
    songs: [
      "darkness-falls",
      "faint-courage",
      "rude-buster",
      "lantern",
      "asgore"
    ]
  },
  {
    id: "asgore",
    name: "Asgore",
    color: "#ffff24",
    source: "asgore",
    songs: [
      "flower-king",
      "that-day"
    ]
  },
  {
    id: "spamton",
    name: "Spamton (motif)",
    color: "#ee80d2",
    source: "spamton",
    songs: [
      "spamton",
      "deal-gone-wrong",
      "big-shot",
      "nows-your-chance-to-be-a",
      "catswing",
      "airwaves"
    ]
  },
  {
    id: "tenna",
    name: "Tenna",
    color: "#f6390f",
    source: "mike-the-board-please",
    songs: [
      "mike-the-board-please",
      "its-tv-time",
      "physical-challenge",
      "adventure-board",
      "tv-world",
      "doom-board",
      "feature-presentation",
      "catswing",
      "metaphysical-challenge",
      "paradise-paradise",
      "big-city-board",
      "raft-ride",
      "sandy-board",
      "quiz",
      "board-clear",
      "sword",
      "query"
    ]
  },
  {
    id: "big-shot",
    name: "BIG SHOT (motif)",
    color: "#88076c",
    source: "big-shot",
    songs: [
      "nows-your-chance-to-be-a",
      "catswing",
      "big-shot"
    ]
  },
  {
    id: "the-holy",
    name: "THE HOLY (motif)",
    color: "#90f1a5",
    source: "the-holy",
    songs: [
      "dump",
      "sword",
      "flashback-excerpt",
      "atrium"
    ]
  },
  {
    id: "your-best-nightmare",
    name: "Your Best Nightmare",
    color: "#950023",
    source: "your-best-nightmare",
    songs: [
      "imminent-death",
      "vs-susie",
      "digital-roots",
      "bit-roots",
    ]
  },
  {
    id: "flowery",
    name: "Flowery",
    color: "#ffdd31",
    source: "your-dads-best-friend",
    songs: [
      "sunset-of-seven-suns",
      "flower-man",
      "petal-dance",
      "dreamwatchers",
      "weak-flowers",
      "goodnight-sweet-prince",
      "beautiful-bathtime"
    ]
  },
  {
    id: "flowers",
    name: "Flowers",
    color: "#4eff37",
    source: "sunset-of-seven-suns",
    songs: [
      "sunset-of-seven-suns",
      "flower-foyer",
      "running-sky",
      "who-might-you-be",
      "stop-criminell",
      "im-telling",
      "petal-dance",
      "flower-castle"
    ]
  }
]
